import { StyleSheet } from 'react-native';
import theme from './theme.styled';

export const AddPatientStyles = StyleSheet.create({
  outer: { flex: 1, backgroundColor: theme.colors.bg },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 14,
    backgroundColor: theme.colors.surface,
    gap: 14,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.surfaceBorder,
    elevation: 2,
    shadowColor: theme.colors.dark,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.colors.background,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  hTitle: {
    fontSize: 19,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.dark,
    letterSpacing: 0.1,
  },
  hSub: {
    fontSize: 10,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.textMuted,
    letterSpacing: 1.2,
    marginTop: 2,
  },
  stepWrap: {
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.surfaceBorder,
    shadowColor: theme.colors.dark,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 2,
  },
  scroll: { flex: 1 },
  formContent: { paddingHorizontal: 16, paddingTop: 16 },
  cardContainer: {
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    shadowColor: theme.colors.dark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
    marginBottom: 16,
  },
  btnRow: { flexDirection: 'row', gap: 12, marginTop: 4 },
  backSecBtn: {
    paddingVertical: 15,
    paddingHorizontal: 22,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: theme.colors.surfaceBorder,
    backgroundColor: theme.colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backSecTxt: { fontSize: 15, fontWeight: theme.fontWeight.bold, color: theme.colors.textSlate },
  nextBtn: {
    flex: 2,
    backgroundColor: theme.colors.primary,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  nextTxt: {
    fontSize: 16,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.surface,
    letterSpacing: 0.4,
  },
  confirmCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    padding: 18,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    shadowColor: theme.colors.dark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  confirmTitle: {
    fontSize: 13,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.dark,
    letterSpacing: 0.5,
    marginBottom: 12,
    textTransform: 'uppercase',
  },
  confirmRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.bg,
  },
  confirmLbl: { fontSize: 13, fontWeight: '600', color: theme.colors.textMuted },
  confirmVal: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.colors.dark,
    flex: 1,
    textAlign: 'right',
  },
  confirmInfoBox: {
    backgroundColor: theme.colors.primarySoft,
    borderRadius: 10,
    padding: 12,
    marginTop: 12,
    borderLeftWidth: 3,
    borderLeftColor: theme.colors.primary,
  },
  confirmInfoTxt: {
    fontSize: 12,
    color: theme.colors.primary,
    fontWeight: '500',
    lineHeight: 18,
  },
});

export const BasicInfoStyles = StyleSheet.create({
  group: { marginBottom: 18 },
  lbl: {
    fontSize: 11,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.textMuted,
    letterSpacing: 1.1,
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  req: { color: theme.colors.danger },
  inp: {
    backgroundColor: theme.colors.surface,
    borderRadius: 12,
    paddingHorizontal: 16,
    height: 50,
    fontSize: 15,
    fontWeight: '400',
    color: theme.colors.dark,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    justifyContent: 'center',
  },
  inpErr: {
    borderColor: theme.colors.danger,
  },
  errTxt: {
    fontSize: 12,
    color: theme.colors.danger,
    marginTop: 5,
    fontWeight: '500',
  },
  inpRow: {
    backgroundColor: theme.colors.surface,
    borderRadius: 12,
    paddingHorizontal: 16,
    height: 50,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  inpTxt: { fontSize: 15, fontWeight: '400', color: theme.colors.dark },
  inpPh: { fontSize: 15, fontWeight: '400', color: theme.colors.textMuted },
  pillRow: { flexDirection: 'row', gap: 10, flexWrap: 'wrap' },
  pill: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: theme.colors.surfaceBorder,
    backgroundColor: theme.colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pillOn: { backgroundColor: theme.colors.primary, borderColor: theme.colors.primary },
  pillTxt: { fontSize: 13, fontWeight: theme.fontWeight.semibold, color: theme.colors.textSlate },
  pillTxtOn: { color: theme.colors.surface },
  imgWrap: { alignItems: 'center', paddingVertical: 10 },
  imgCircle: {
    width: 90,
    height: 90,
    borderRadius: 45,
    position: 'relative',
    marginBottom: 8,
  },
  imgPreview: {
    width: 90,
    height: 90,
    borderRadius: 45,
    borderWidth: 2.5,
    borderColor: theme.colors.primary,
  },
  imgPlaceholder: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: theme.colors.background,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: theme.colors.surfaceBorder,
  },
  imgPlaceholderTxt: { fontSize: 36 },
  imgCameraBtn: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: theme.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: theme.colors.surface,
  },
  imgHint: { fontSize: 12, color: theme.colors.textMuted, fontWeight: '500' },
  lockedRow: {
    backgroundColor: theme.colors.primarySoft,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.mintBdr,
  },
  lockedTxt: {
    fontSize: 15,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.primary,
    flex: 1,
    marginRight: 8,
  },
  lockedHint: { fontSize: 11, color: theme.colors.textMuted, marginTop: 5, fontStyle: 'italic' },
});

export const ContactInfoStyles = StyleSheet.create({
  group: { marginBottom: 18 },
  lbl: {
    fontSize: 11,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.textMuted,
    letterSpacing: 1.1,
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  req: { color: theme.colors.danger },
  inp: {
    backgroundColor: theme.colors.surface,
    borderRadius: 12,
    paddingHorizontal: 16,
    height: 50,
    fontSize: 15,
    fontWeight: '400',
    color: theme.colors.dark,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    justifyContent: 'center',
  },
  inpErr: {
    borderColor: theme.colors.danger,
  },
  inpRow: {
    backgroundColor: theme.colors.surface,
    borderRadius: 12,
    paddingHorizontal: 16,
    height: 50,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  inpTxt: { fontSize: 15, fontWeight: '400', color: theme.colors.dark },
  inpPh: { fontSize: 15, fontWeight: '400', color: theme.colors.textMuted },
  errTxt: {
    fontSize: 12,
    color: theme.colors.danger,
    marginTop: 5,
    fontWeight: '500',
  },
  infoBox: {
    backgroundColor: theme.colors.primarySoft,
    borderRadius: 12,
    padding: 14,
    flexDirection: 'row',
    gap: 10,
    marginBottom: 8,
    borderLeftWidth: 3,
    borderLeftColor: theme.colors.primary,
  },
  infoTxt: {
    flex: 1,
    fontSize: 13,
    fontWeight: '500',
    color: theme.colors.primary,
    lineHeight: 20,
  },
});

export const MedicalInfoStyles = StyleSheet.create({
  group: { marginBottom: 18 },
  lbl: {
    fontSize: 11,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.textMuted,
    letterSpacing: 1.1,
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  inp: {
    backgroundColor: theme.colors.surface,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
    fontWeight: '400',
    color: theme.colors.dark,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  infoBox: {
    backgroundColor: theme.colors.primarySoft,
    borderRadius: 12,
    padding: 14,
    flexDirection: 'row',
    gap: 10,
    marginBottom: 8,
    borderLeftWidth: 3,
    borderLeftColor: theme.colors.primary,
  },
  infoTxt: {
    flex: 1,
    fontSize: 13,
    fontWeight: '500',
    color: theme.colors.primary,
    lineHeight: 20,
  },
});
