import { StyleSheet } from 'react-native';
import { theme } from './theme.styled';

export const createPrescriptionStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },

  // ----------------------------------------------------
  // Screen Header Bar
  // ----------------------------------------------------
  headerContainer: {
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.surfaceBorder,
    shadowColor: theme.colors.dark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 3,
  },
  backButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: theme.colors.surfaceSecondary,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  headerTitleGroup: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: theme.colors.textPrimary,
    letterSpacing: -0.2,
  },
  headerSubtitle: {
    fontSize: 12,
    fontWeight: '500',
    color: theme.colors.textSlate,
    marginTop: 1,
  },
  headerBadge: {
    backgroundColor: theme.colors.primarySoft,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: theme.colors.mintBdr,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: theme.colors.primary,
  },

  // ----------------------------------------------------
  // Multi-Step Navigation Tabs
  // ----------------------------------------------------
  stepBarWrapper: {
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.surfaceBorder,
  },
  stepBarContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  stepTab: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: theme.colors.surfaceSecondary,
    borderWidth: 1,
    borderColor: 'transparent',
    gap: 6,
  },
  stepTabActive: {
    backgroundColor: theme.colors.primarySoft,
    borderColor: theme.colors.mintBdr,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  stepTabBadge: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: theme.colors.surfaceBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepTabBadgeActive: {
    backgroundColor: theme.colors.primary,
  },
  stepTabBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: theme.colors.textSlate,
  },
  stepTabBadgeTextActive: {
    color: theme.colors.surface,
  },
  stepTabTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.colors.textSlate,
  },
  stepTabTitleActive: {
    color: theme.colors.primary,
    fontWeight: '700',
  },

  // Legacy Consult Tab Bar Aliases
  consultStepBarWrapper: {
    backgroundColor: theme.colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.surfaceBorder,
    flexDirection: 'row',
    alignItems: 'center',
  },
  consultStepTab: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  consultStepTabActive: {
    borderBottomColor: theme.colors.primary,
  },
  consultStepTabTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.colors.textSlate,
  },
  consultStepTabTitleActive: {
    color: theme.colors.primary,
    fontWeight: '700',
  },

  // ----------------------------------------------------
  // Form Section Cards & Input Controls
  // ----------------------------------------------------
  consultSectionCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    shadowColor: theme.colors.dark,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 2,
  },
  consultSectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: theme.colors.textPrimary,
    marginBottom: 12,
  },
  consultTextArea: {
    backgroundColor: '#F8FAFC',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: theme.colors.textPrimary,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    minHeight: 80,
  },
  consultInput: {
    backgroundColor: '#F8FAFC',
    borderRadius: 10,
    paddingHorizontal: 12,
    height: 44,
    fontSize: 14,
    color: theme.colors.textPrimary,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  consultDateBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F8FAFC',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    paddingHorizontal: 12,
    height: 44,
  },

  // Vitals Controls
  vitalLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.colors.textSecondary,
    marginBottom: 4,
  },
  vitalsRow: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  vitalInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    borderRadius: 10,
    backgroundColor: '#F8FAFC',
    overflow: 'hidden',
    height: 44,
  },
  vitalInput: {
    flex: 1,
    paddingHorizontal: 10,
    fontSize: 14,
    color: theme.colors.textPrimary,
  },
  vitalUnitTag: {
    backgroundColor: theme.colors.surfaceSecondary,
    paddingHorizontal: 10,
    height: '100%',
    justifyContent: 'center',
    borderLeftWidth: 1,
    borderLeftColor: theme.colors.surfaceBorder,
  },
  vitalUnitText: {
    fontSize: 11,
    fontWeight: '700',
    color: theme.colors.textSlate,
  },
  bmiContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceSecondary,
    borderRadius: 10,
    paddingHorizontal: 12,
    height: 44,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  bmiAutoTag: {
    backgroundColor: theme.colors.primarySoft,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: theme.colors.mintBdr,
  },
  bmiAutoText: {
    fontSize: 10,
    fontWeight: '700',
    color: theme.colors.primary,
  },

  // Medication Cards
  medCardHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.surfaceSecondary,
  },
  medNumBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: theme.colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  medNumText: {
    fontSize: 12,
    fontWeight: '700',
    color: theme.colors.primary,
  },
  medCardTitle: {
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
    color: theme.colors.textPrimary,
  },
  removeText: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.colors.danger,
  },
  pickerSelectBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F8FAFC',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    paddingHorizontal: 12,
    height: 44,
  },
  pickerSelectText: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.colors.textPrimary,
  },
  unitSelectBtn: {
    backgroundColor: theme.colors.surfaceSecondary,
    borderWidth: 1,
    borderLeftWidth: 0,
    borderColor: theme.colors.surfaceBorder,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    paddingHorizontal: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  unitSelectText: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.colors.primary,
  },

  // Action Buttons
  addPrimaryBtn: {
    backgroundColor: theme.colors.primarySoft,
    borderWidth: 1,
    borderColor: theme.colors.mintBdr,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addPrimaryBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: theme.colors.primary,
  },
  addOutlineBtn: {
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addOutlineBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.colors.primary,
  },
  draftBtn: {
    backgroundColor: theme.colors.surfaceSecondary,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    borderRadius: theme.borderRadius.lg,
    paddingVertical: 12,
    marginHorizontal: theme.spacing.lg,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  draftBtnText: {
    fontSize: theme.fontSize.sm,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textSecondary,
    fontFamily: 'Inter_600SemiBold',
  },

  // ----------------------------------------------------
  // Sticky Bottom Navigation Bar
  // ----------------------------------------------------
  stickyBottomBar: {
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 14,
    borderTopWidth: 1,
    borderTopColor: theme.colors.surfaceBorder,
    shadowColor: theme.colors.dark,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 10,
  },
  consultStickyBottomBar: {
    backgroundColor: theme.colors.surface,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 14,
    borderTopWidth: 1,
    borderTopColor: theme.colors.surfaceBorder,
    shadowColor: theme.colors.dark,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 10,
  },
  autoSaveRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
    gap: 6,
  },
  autoSaveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: theme.colors.success,
  },
  autoSaveText: {
    fontSize: 11,
    color: theme.colors.textMuted,
    fontWeight: '500',
  },
  bottomBtnRow: {
    flexDirection: 'row',
    gap: 10,
  },
  btnPrev: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: theme.colors.surfaceSecondary,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    alignItems: 'center',
  },
  btnPrevText: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.colors.textSecondary,
  },
  btnNext: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: theme.colors.primary,
    alignItems: 'center',
  },
  btnNextText: {
    fontSize: 13,
    fontWeight: '700',
    color: theme.colors.surface,
  },
  btnComplete: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: theme.colors.primary,
    alignItems: 'center',
  },
  btnCompleteText: {
    fontSize: 13,
    fontWeight: '700',
    color: theme.colors.surface,
  },
});

export default createPrescriptionStyles;
