import { StyleSheet } from 'react-native';
import { theme } from './theme.styled';

export const editPatientStyles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: theme.colors.primary,
  },
  backCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  backArrow: {
    fontSize: 20,
    color: theme.colors.surface,
    lineHeight: 30,
  },
  headerTitle: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: theme.colors.surface,
    marginLeft: 12,
  },
  idBadge: {
    backgroundColor: theme.colors.primarySoft,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: theme.colors.mintBdr,
  },
  idBadgeTxt: {
    fontSize: 11,
    fontWeight: '600',
    color: theme.colors.primary,
  },
  sectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 16,
    marginTop: 18,
    marginBottom: 10,
  },
  sectionBar: {
    width: 4,
    height: 20,
    borderRadius: 2,
    marginRight: 10,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.colors.textPrimary,
    flex: 1,
  },
  cantEditBadge: {
    backgroundColor: theme.colors.surfaceSecondary,
    borderRadius: 8,
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  cantEditTxt: {
    fontSize: 9,
    fontWeight: '500',
    color: theme.colors.textMuted,
  },
  card: {
    backgroundColor: theme.colors.surface,
    marginHorizontal: 16,
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  inputGroup: {
    marginBottom: 14,
  },
  label: {
    fontSize: 12,
    fontWeight: '500',
    color: theme.colors.textSecondary,
    marginBottom: 6,
  },
  lockedInput: {
    backgroundColor: theme.colors.surfaceSecondary,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  lockedText: {
    fontSize: 13,
    color: theme.colors.textMuted,
    fontWeight: '400',
  },
  readOnlyCard: {
    backgroundColor: theme.colors.surface,
    marginHorizontal: 16,
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  readOnlyHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  readOnlyAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#EEF2FF',
    borderWidth: 1.5,
    borderColor: '#C7D2FE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  readOnlyAvatarTxt: {
    fontSize: 13,
    fontWeight: '600',
    color: '#4F46E5',
  },
  readOnlyHeaderInfo: {
    flex: 1,
    marginLeft: 12,
  },
  readOnlyName: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.textPrimary,
  },
  readOnlySubRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
  },
  readOnlyId: {
    fontSize: 11,
    fontWeight: '500',
    color: theme.colors.textMuted,
  },
  viewOnlyTag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  viewOnlyTagTxt: {
    fontSize: 9,
    fontWeight: '500',
    color: '#64748B',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  readOnlyNotice: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#EDF2F7',
  },
  readOnlyNoticeTxt: {
    fontSize: 10,
    fontWeight: '400',
    color: '#64748B',
    flex: 1,
    marginLeft: 7,
    lineHeight: 15,
  },
  readOnlyDetailsList: {
    gap: 8,
  },
  readOnlyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderRadius: 10,
    padding: 10,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  readOnlyIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  readOnlyMeta: {
    flex: 1,
  },
  readOnlyLabel: {
    fontSize: 9,
    fontWeight: '500',
    color: theme.colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 2,
  },
  readOnlyValue: {
    fontSize: 12,
    fontWeight: '500',
    color: theme.colors.textPrimary,
  },
  readOnlyGridRow: {
    flexDirection: 'row',
    gap: 8,
  },
  readOnlyGridItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderRadius: 10,
    padding: 10,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  input: {
    backgroundColor: theme.colors.background,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 11,
    fontSize: 13,
    color: theme.colors.textPrimary,
  },
  textArea: {
    minHeight: 80,
    textAlignVertical: 'top',
  },
  picker: {
    backgroundColor: theme.colors.background,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  pickerTxt: {
    fontSize: 13,
    color: theme.colors.textPrimary,
    fontWeight: '400',
  },
  chevron: {
    fontSize: 10,
    color: theme.colors.textMuted,
  },
  row: {
    flexDirection: 'row',
  },
  bmiBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.primarySoft,
    borderWidth: 1,
    borderColor: theme.colors.mintBdr,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  bmiVal: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.colors.primary,
    marginRight: 6,
  },
  bmiUnit: {
    fontSize: 11,
    color: theme.colors.primaryDark,
    fontWeight: '500',
  },
  btnRow: {
    flexDirection: 'row',
    gap: 12,
    marginHorizontal: 16,
    marginTop: 20,
  },
  cancelBtn: {
    flex: 1,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
  },
  cancelTxt: {
    fontSize: 13,
    fontWeight: '500',
    color: theme.colors.textSecondary,
  },
  saveBtn: {
    flex: 1.5,
    backgroundColor: theme.colors.primary,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
  },
  saveTxt: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.colors.surface,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: theme.colors.surface,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 16,
  },
  modalHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.surfaceBorder,
  },
  modalTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.colors.textPrimary,
  },
  modalClose: {
    fontSize: 16,
    color: theme.colors.textMuted,
    fontWeight: '500',
  },
  modalOpt: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.surfaceSecondary,
  },
  modalOptSelected: {
    backgroundColor: theme.colors.primarySoft,
  },
  modalOptTxt: {
    fontSize: 13,
    color: theme.colors.textSecondary,
  },
  modalOptTxtSelected: {
    color: theme.colors.primary,
    fontWeight: '600',
  },
  checkmark: {
    fontSize: 14,
    color: theme.colors.primary,
    fontWeight: '600',
  },
});
