import { StyleSheet } from 'react-native';
import { theme } from './theme.styled';

export const emrUploadModalStyles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.55)',
    justifyContent: 'flex-end',
  },
  sheetContainer: {
    backgroundColor: theme.colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 28,
    maxHeight: '92%',
    shadowColor: theme.colors.dark,
    shadowOffset: { width: 0, height: -6 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 12,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 4,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.textPrimary,
    letterSpacing: -0.2,
  },
  headerSubtitle: {
    fontSize: 13,
    color: theme.colors.textSlate,
    marginTop: 2,
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: theme.colors.surfaceSecondary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeButtonText: {
    fontSize: 16,
    color: theme.colors.textSlate,
    fontWeight: theme.fontWeight.bold,
  },
  headerDivider: {
    height: 1,
    backgroundColor: theme.colors.surfaceSecondary,
    marginVertical: 14,
  },
  formContainer: {
    gap: 16,
  },
  fieldGroup: {
    marginBottom: 2,
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textSecondary,
    marginBottom: 6,
  },
  asterisk: {
    color: theme.colors.danger,
  },
  selectBox: {
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  selectBoxError: {
    borderColor: theme.colors.danger,
  },
  selectPlaceholder: {
    fontSize: 14,
    color: theme.colors.textMuted,
  },
  selectValueText: {
    fontSize: 14,
    color: theme.colors.textPrimary,
    fontWeight: theme.fontWeight.medium,
  },
  caretIcon: {
    fontSize: 12,
    color: theme.colors.textMuted,
  },
  textInput: {
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    color: theme.colors.textPrimary,
  },
  textInputError: {
    borderColor: theme.colors.danger,
  },
  notesInput: {
    minHeight: 84,
    textAlignVertical: 'top',
  },
  chooseFileBox: {
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: '#CBD5E1',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FAFBFD',
  },
  chooseFileBoxError: {
    borderColor: theme.colors.danger,
  },
  chooseFileText: {
    fontSize: 14,
    fontWeight: theme.fontWeight.semibold,
    color: '#475569',
  },
  selectedFileBadge: {
    backgroundColor: theme.colors.primarySoft,
    borderWidth: 1,
    borderColor: theme.colors.mintBdr,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  selectedFileLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: 10,
    gap: 8,
  },
  selectedFileName: {
    fontSize: 13,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.primary,
    flex: 1,
  },
  removeFileBtn: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#FEE2E2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  removeFileTxt: {
    fontSize: 12,
    color: theme.colors.danger,
    fontWeight: theme.fontWeight.bold,
  },
  shareContainer: {
    backgroundColor: '#ECFDF5',
    borderWidth: 1,
    borderColor: '#A7F3D0',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  shareTextWrap: {
    flex: 1,
    marginRight: 12,
  },
  shareTitle: {
    fontSize: 14,
    fontWeight: theme.fontWeight.bold,
    color: '#065F46',
    marginBottom: 2,
  },
  shareSubtitle: {
    fontSize: 12,
    color: '#047857',
  },
  toggleSwitch: {
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 6,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 46,
  },
  toggleSwitchOn: {
    backgroundColor: '#059669',
  },
  toggleSwitchOff: {
    backgroundColor: '#9CA3AF',
  },
  toggleSwitchText: {
    fontSize: 12,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.textInverted,
  },
  uploadButton: {
    backgroundColor: theme.colors.primary,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 3,
  },
  uploadButtonText: {
    fontSize: 16,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.textInverted,
  },
  errorText: {
    fontSize: 12,
    color: theme.colors.danger,
    marginTop: 4,
  },

  // Inline Category Dropdown List
  inlineDropdownList: {
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    borderRadius: 12,
    marginTop: 4,
    overflow: 'hidden',
    shadowColor: theme.colors.dark,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  inlineDropdownItem: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.surfaceSecondary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  inlineDropdownItemActive: {
    backgroundColor: theme.colors.primarySoft,
  },
  inlineDropdownText: {
    fontSize: 14,
    color: theme.colors.textPrimary,
    fontWeight: theme.fontWeight.medium,
  },
  inlineDropdownTextActive: {
    color: theme.colors.primary,
    fontWeight: theme.fontWeight.bold,
  },
});

export default emrUploadModalStyles;
