import { Dimensions, StyleSheet } from 'react-native';
import { globalShadows, theme } from './theme.styled';

const { width } = Dimensions.get('window');

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  scrollContent: {
    paddingTop: theme.spacing.md,
    paddingHorizontal: theme.spacing.lg,
    paddingBottom: 40,
  },

  // Search Input Bar
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderRadius: theme.borderRadius.md,
    paddingHorizontal: theme.spacing.md,
    height: 48,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    marginBottom: theme.spacing.xl,
    ...globalShadows.card,
  },
  searchInput: {
    flex: 1,
    marginLeft: theme.spacing.sm,
    fontSize: 13,
    color: theme.colors.textPrimary,
  },

  // Highlights & Insights Section
  insightsSection: {
    marginBottom: theme.spacing.xl,
  },
  insightsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: theme.spacing.md,
  },
  insightsTitle: {
    fontSize: 15,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textPrimary,
  },
  periodPill: {
    backgroundColor: theme.colors.primarySoft,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: theme.colors.mintBdr,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  periodPillText: {
    fontSize: 11,
    fontWeight: theme.fontWeight.medium,
    color: theme.colors.primary,
  },
  screenBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
  },
  periodDropdownMenu: {
    ...globalShadows.card,
    position: 'absolute',
    zIndex: 100,
    elevation: 10,
    backgroundColor: theme.colors.surface,
    borderRadius: theme.borderRadius.md,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    minWidth: 140,
    overflow: 'hidden',
  },
  periodMenuItem: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.surfaceSecondary,
  },
  periodMenuItemText: {
    fontSize: 11,
    color: theme.colors.textPrimary,
  },
  periodMenuItemTextActive: {
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.primary,
  },

  // Stat Tile
  statTile: {
    width: 152,
    backgroundColor: theme.colors.surface,
    borderRadius: 20,
    padding: 16,
    marginRight: theme.spacing.md,
    borderWidth: 1,
    borderColor: 'rgba(226, 232, 240, 0.8)',
    ...globalShadows.card,
  },
  statTileTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  statIconWrapper: {
    width: 42,
    height: 42,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  statTileValue: {
    fontSize: 22,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textPrimary,
    marginBottom: 3,
  },
  statTileLabel: {
    fontSize: 11,
    fontWeight: theme.fontWeight.medium,
    color: theme.colors.textSlate,
  },

  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: theme.spacing.md,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textPrimary,
  },
  sectionLink: {
    fontSize: 12,
    color: theme.colors.primary,
    fontWeight: theme.fontWeight.medium,
  },

  appointmentCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: 'rgba(226, 232, 240, 0.9)',
    ...globalShadows.card,
  },
  apptHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 12,
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  timeGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 1,
  },
  timePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  apptTime: {
    fontSize: 11.5,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textPrimary,
  },
  liveStatusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: '#DCFCE7',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#86EFAC',
  },
  liveStatusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#16A34A',
  },
  liveStatusText: {
    fontSize: 10,
    fontWeight: theme.fontWeight.semibold,
    color: '#15803D',
  },
  apptDistanceBadge: {
    backgroundColor: theme.colors.surfaceSecondary,
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 10,
  },
  apptDistance: {
    fontSize: 10,
    fontWeight: theme.fontWeight.medium,
    color: theme.colors.textSlate,
  },
  consultBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4.5,
    borderRadius: 20,
    gap: 5,
    borderWidth: 1,
    flexShrink: 0,
  },
  consultBadgeVideo: {
    backgroundColor: theme.colors.primarySoft,
    borderColor: theme.colors.mintBdr,
  },
  consultBadgeClinic: {
    backgroundColor: '#FFF7ED',
    borderColor: '#FED7AA',
  },
  consultBadgeText: {
    fontSize: 10.5,
    fontWeight: theme.fontWeight.semibold,
    letterSpacing: 0.2,
  },
  apptPatientRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  apptAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.primary,
    borderWidth: 2,
    borderColor: '#CCFBF1',
    marginRight: 12,
    flexShrink: 0,
  },
  apptAvatarText: {
    fontSize: 13,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textInverted,
    letterSpacing: 0.5,
  },
  patientInfoGroup: {
    flex: 1,
    justifyContent: 'center',
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  apptPatientName: {
    fontSize: 13,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textPrimary,
    letterSpacing: 0.1,
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginLeft: 6,
  },
  patientMetaText: {
    fontSize: 11,
    color: theme.colors.textSlate,
    fontWeight: theme.fontWeight.regular,
    marginTop: 2,
  },
  apptIdBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    marginTop: 4,
  },
  aptIdText: {
    fontSize: 10,
    color: theme.colors.textSlate,
    fontWeight: theme.fontWeight.medium,
    letterSpacing: 0.2,
  },
  chevronWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: 8,
  },
  symptomsContainer: {
    backgroundColor: '#F8FAFC',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderLeftWidth: 3.5,
    borderLeftColor: theme.colors.primary,
    marginBottom: 12,
  },
  symptomsText: {
    fontSize: 11,
    color: theme.colors.textSecondary,
    lineHeight: 16,
  },
  symptomsLabel: {
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textPrimary,
  },
  apptFooterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#F8FAFC',
  },
  footerLeftGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  viewDetailsBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingVertical: 4,
    paddingRight: 8,
  },
  viewDetailsText: {
    fontSize: 11,
    fontWeight: theme.fontWeight.medium,
    color: theme.colors.primary,
  },
  detailsBtn: {
    backgroundColor: theme.colors.primary,
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 16,
    flexShrink: 0,
    alignSelf: 'center',
  },
  detailsBtnText: {
    fontSize: 11,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textInverted,
  },
  grayDisabled: {
    fontSize: 10,
    fontWeight: theme.fontWeight.medium,
    color: theme.colors.textMuted,
  },
  joinBtn: {
    backgroundColor: theme.colors.primary,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginLeft: 'auto',
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  joinBtnDisabled: {
    backgroundColor: theme.colors.grayDisabled,
    shadowOpacity: 0,
    elevation: 0,
  },
  joinBtnText: {
    fontSize: 11,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textInverted,
    letterSpacing: 0.2,
  },
  joinBtnTextDisabled: {
    color: theme.colors.grayText,
  },

  // Need Assistance Banner
  supportBanner: {
    backgroundColor: theme.colors.accent,
    borderRadius: theme.borderRadius.lg,
    padding: theme.spacing.xl,
    marginBottom: theme.spacing.xl,
    overflow: 'hidden',
    position: 'relative',
    ...globalShadows.card,
  },
  supportCircle1: {
    position: 'absolute',
    right: -20,
    top: -20,
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
  },
  supportCircle2: {
    position: 'absolute',
    right: 40,
    bottom: -35,
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
  },
  supportTitle: {
    fontSize: 15,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textInverted,
    marginBottom: 6,
  },
  supportSub: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.85)',
    lineHeight: 16,
    marginBottom: theme.spacing.lg,
  },
  supportBtn: {
    backgroundColor: theme.colors.surface,
    alignSelf: 'flex-start',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 22,
  },
  supportBtnText: {
    fontSize: 12,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.accent,
  },

  // Quick Access 2x2 Grid
  quickAccessGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: theme.spacing.md,
  },
  quickAccessCard: {
    width: (width - 44) / 2,
    backgroundColor: theme.colors.surface,
    borderRadius: theme.borderRadius.lg,
    paddingVertical: theme.spacing.xl,
    paddingHorizontal: theme.spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    ...globalShadows.card,
  },
  quickAccessLabel: {
    fontSize: 10,
    fontWeight: theme.fontWeight.medium,
    color: theme.colors.textSecondary,
    letterSpacing: 0.4,
    marginTop: 8,
    textAlign: 'center',
  },
  emptyCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 36,
    alignItems: 'center',
    shadowColor: '#1E293B',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    marginBottom: 20,
  },
  emptyText: {
    fontSize: 13,
    fontWeight: theme.fontWeight.medium,
    color: '#94A3B8',
    marginBottom: 5,
    textAlign: 'center',
    fontFamily: 'Inter_500Medium',
  },
  emptySub: {
    fontSize: 11,
    color: '#CBD5E1',
    textAlign: 'center',
    fontFamily: 'Inter_400Regular',
  },
  bookNowBtn: {
    backgroundColor: theme.colors.primary,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    marginTop: 12,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  bookNowBtnText: {
    fontSize: 12,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textInverted,
  },
});
