import { StyleSheet } from 'react-native';
import { theme } from './theme.styled';

export const patientProfileTabStyles = StyleSheet.create({
  editProfileBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: theme.borderRadius.sm || 10,
    backgroundColor: theme.colors.surface,
    borderWidth: 1.5,
    borderColor: theme.colors.primary,
    alignSelf: 'flex-end',
  },
  editProfileBtnText: {
    fontSize: theme.fontSize.xs || 13,
    fontWeight: theme.fontWeight.bold || '700',
    color: theme.colors.primary,
  },
  card: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.borderRadius.md || 14,
    marginHorizontal: theme.spacing.md || 14,
    marginTop: theme.spacing.md || 12,
    overflow: 'hidden',
    elevation: 1,
    shadowColor: theme.colors.dark,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
  },
  cardSectionTitle: {
    fontSize: theme.fontSize.xs || 13,
    fontWeight: theme.fontWeight.bold || '800',
    color: theme.colors.textPrimary,
    marginBottom: theme.spacing.md || 12,
    marginHorizontal: theme.spacing.md || 14,
    marginTop: theme.spacing.md || 14,
    letterSpacing: 0.1,
    textTransform: 'uppercase',
  },
  divider: {
    height: 1,
    backgroundColor: theme.colors.surfaceSecondary,
    marginHorizontal: theme.spacing.md || 14,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingVertical: 11,
    paddingHorizontal: theme.spacing.md || 14,
    gap: 12,
  },
  infoLabel: {
    fontSize: theme.fontSize.xs || 12,
    color: theme.colors.textMuted,
    fontWeight: '600',
    flex: 1,
  },
  infoValue: {
    fontSize: theme.fontSize.xs || 13,
    color: theme.colors.textPrimary,
    fontWeight: '600',
    flex: 2,
    textAlign: 'right',
  },
  vitalsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    paddingHorizontal: theme.spacing.md || 14,
    paddingBottom: theme.spacing.md || 14,
  },
  vitalBox: {
    flex: 1,
    minWidth: 72,
    alignItems: 'center',
    padding: 12,
    backgroundColor: theme.colors.background,
    borderRadius: theme.borderRadius.md || 12,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  vitalValue: {
    fontSize: theme.fontSize.sm || 15,
    fontWeight: theme.fontWeight.bold || '800',
    color: theme.colors.textPrimary,
  },
  vitalLabel: {
    fontSize: 10,
    color: theme.colors.textSlate,
    fontWeight: '600',
    marginTop: 3,
  },
  alertBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: 12,
    borderRadius: theme.borderRadius.sm || 10,
    borderWidth: 1,
    marginHorizontal: theme.spacing.md || 14,
    marginBottom: 10,
  },
  alertLabel: {
    fontSize: theme.fontSize.xs || 12,
    fontWeight: theme.fontWeight.bold || '700',
    marginBottom: 3,
  },
  alertText: {
    fontSize: theme.fontSize.xs || 13,
    color: theme.colors.textSecondary,
    lineHeight: 18,
  },
  familyHeaderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: theme.spacing.md || 14,
    marginTop: theme.spacing.md || 14,
    marginBottom: theme.spacing.sm || 8,
  },
  familyHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  familySectionTag: {
    backgroundColor: theme.colors.mintBg || '#CCFBF1',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: theme.borderRadius.full || 9999,
    borderWidth: 1,
    borderColor: theme.colors.mintBdr || '#99F6E4',
  },
  familySectionTagText: {
    fontSize: 10,
    fontWeight: theme.fontWeight.bold || '700',
    color: theme.colors.primary || '#0F766E',
    textTransform: 'uppercase',
  },
  familyCardList: {
    paddingHorizontal: theme.spacing.md || 14,
    paddingBottom: theme.spacing.md || 14,
    gap: 12,
  },
  familyMemberCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.borderRadius.md || 12,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder || '#E2E8F0',
    padding: 12,
  },
  familyCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    gap: 10,
  },
  familyAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.colors.primarySoft || '#F0FDFA',
    borderWidth: 1.5,
    borderColor: theme.colors.tealBdr || '#99F6E4',
    justifyContent: 'center',
    alignItems: 'center',
  },
  familyAvatarText: {
    fontSize: theme.fontSize.sm || 14,
    fontWeight: theme.fontWeight.bold || '700',
    color: theme.colors.primary || '#0F766E',
  },
  familyHeaderInfo: {
    flex: 1,
  },
  familyMemberName: {
    fontSize: theme.fontSize.sm || 14,
    fontWeight: theme.fontWeight.bold || '700',
    color: theme.colors.textPrimary || '#0F172A',
    marginBottom: 2,
  },
  familyHeaderBadges: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexWrap: 'wrap',
  },
  relationBadge: {
    backgroundColor: theme.colors.accentLight || '#E0F2FE',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: theme.borderRadius.sm || 6,
  },
  relationBadgeText: {
    fontSize: 10,
    fontWeight: theme.fontWeight.semibold || '600',
    color: theme.colors.accent || '#0284C7',
    textTransform: 'capitalize',
  },
  patientIdPill: {
    backgroundColor: theme.colors.surfaceSecondary || '#F1F5F9',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: theme.borderRadius.sm || 6,
  },
  patientIdPillText: {
    fontSize: 10,
    fontWeight: theme.fontWeight.semibold || '600',
    color: theme.colors.textSlate || '#64748B',
  },
  familyCardBody: {
    backgroundColor: theme.colors.background || '#F8FAFC',
    borderRadius: theme.borderRadius.sm || 8,
    padding: 10,
    gap: 6,
  },
  familyDetailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  familyDetailLabel: {
    fontSize: theme.fontSize.xs || 12,
    color: theme.colors.textMuted || '#94A3B8',
    fontWeight: '500',
  },
  familyDetailValue: {
    fontSize: theme.fontSize.xs || 12,
    color: theme.colors.textSecondary || '#334155',
    fontWeight: '600',
  },
  emptyFamilyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    height: 200,
  },
  emptyFamilyText: {
    fontSize: theme.fontSize.xs || 12,
    color: theme.colors.textMuted || '#94A3B8',
    fontWeight: '500',
  },
});
