import { StyleSheet } from 'react-native';
import { theme } from './theme.styled';

export const patientProfileTabStyles = StyleSheet.create({
  editProfileBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: theme.borderRadius.sm || 10,
    backgroundColor: theme.colors.surface,
    borderWidth: 1.5,
    borderColor: theme.colors.primary,
    alignSelf: 'flex-start',
  },
  editProfileBtnText: {
    fontSize: theme.fontSize.xs || 13,
    fontWeight: theme.fontWeight.bold || '700',
    color: theme.colors.primary,
  },
  card: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.borderRadius.md || 14,
    marginHorizontal: theme.spacing.md || 14,
    marginTop: theme.spacing.md || 12,
    overflow: 'hidden',
    elevation: 1,
    shadowColor: theme.colors.dark,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
  },
  cardSectionTitle: {
    fontSize: theme.fontSize.xs || 13,
    fontWeight: theme.fontWeight.bold || '800',
    color: theme.colors.textPrimary,
    marginBottom: theme.spacing.md || 12,
    marginHorizontal: theme.spacing.md || 14,
    marginTop: theme.spacing.md || 14,
    letterSpacing: 0.1,
    textTransform: 'uppercase',
  },
  divider: {
    height: 1,
    backgroundColor: theme.colors.surfaceSecondary,
    marginHorizontal: theme.spacing.md || 14,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingVertical: 11,
    paddingHorizontal: theme.spacing.md || 14,
    gap: 12,
  },
  infoLabel: {
    fontSize: theme.fontSize.xs || 12,
    color: theme.colors.textMuted,
    fontWeight: '600',
    flex: 1,
  },
  infoValue: {
    fontSize: theme.fontSize.xs || 13,
    color: theme.colors.textPrimary,
    fontWeight: '600',
    flex: 2,
    textAlign: 'right',
  },
  vitalsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    paddingHorizontal: theme.spacing.md || 14,
    paddingBottom: theme.spacing.md || 14,
  },
  vitalBox: {
    flex: 1,
    minWidth: 72,
    alignItems: 'center',
    padding: 12,
    backgroundColor: theme.colors.background,
    borderRadius: theme.borderRadius.md || 12,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  vitalValue: {
    fontSize: theme.fontSize.sm || 15,
    fontWeight: theme.fontWeight.bold || '800',
    color: theme.colors.textPrimary,
  },
  vitalLabel: {
    fontSize: 10,
    color: theme.colors.textSlate,
    fontWeight: '600',
    marginTop: 3,
  },
  alertBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: 12,
    borderRadius: theme.borderRadius.sm || 10,
    borderWidth: 1,
    marginHorizontal: theme.spacing.md || 14,
    marginBottom: 10,
  },
  alertLabel: {
    fontSize: theme.fontSize.xs || 12,
    fontWeight: theme.fontWeight.bold || '700',
    marginBottom: 3,
  },
  alertText: {
    fontSize: theme.fontSize.xs || 13,
    color: theme.colors.textSecondary,
    lineHeight: 18,
  },
});
