import { StyleSheet } from 'react-native';
import { globalShadows, theme } from './theme.styled';

export const patientDetailsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },

  // Top Header Bar
  topBar: {
    height: 65,
    backgroundColor: theme.colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: theme.spacing.lg,
  },
  backCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backArrow: {
    fontSize: 24,
    color: theme.colors.textInverted,
    fontWeight: theme.fontWeight.bold,
    marginTop: -2,
  },
  topBarTitleContainer: {
    flex: 1,
    marginLeft: theme.spacing.md,
  },
  topBarTitle: {
    fontSize: 16,
    color: theme.colors.textInverted,
    fontWeight: theme.fontWeight.bold,
    fontFamily: 'Inter_700Bold',
  },
  topBarSubTitle: {
    fontSize: 11,
    color: 'rgba(255, 255, 255, 0.78)',
    fontFamily: 'Inter_500Medium',
    marginTop: 1,
  },

  // Patient Header Profile Card
  profileCard: {
    backgroundColor: theme.colors.surface,
    marginHorizontal: theme.spacing.lg,
    marginTop: theme.spacing.lg,
    marginBottom: theme.spacing.md,
    borderRadius: theme.borderRadius.lg,
    padding: theme.spacing.lg,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    ...globalShadows.card,
  },
  profileCardInner: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  profileAvatar: {
    width: 62,
    height: 62,
    borderRadius: 31,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  profileAvatarText: {
    fontSize: 22,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.textInverted,
    fontFamily: 'Inter_700Bold',
  },
  profileInfoGroup: {
    flex: 1,
    marginLeft: theme.spacing.lg,
  },
  profileName: {
    fontSize: theme.fontSize.lg,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.textPrimary,
    fontFamily: 'Inter_700Bold',
  },
  profileIdText: {
    fontSize: theme.fontSize.xs,
    color: theme.colors.textSlate,
    marginTop: 2,
    fontFamily: 'Inter_500Medium',
  },
  profileChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: theme.spacing.sm,
  },
  profileChip: {
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 12,
    backgroundColor: theme.colors.primarySoft,
    borderWidth: 1,
    borderColor: theme.colors.mintBdr,
  },
  profileChipText: {
    fontSize: 11,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.primary,
    fontFamily: 'Inter_700Bold',
  },

  // Main Tab Navigation Bar
  mainTabBar: {
    flexDirection: 'row',
    backgroundColor: theme.colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.surfaceBorder,
    paddingHorizontal: theme.spacing.xs,
  },
  mainTab: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 14,
    position: 'relative',
  },
  mainTabLabel: {
    fontSize: 12,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textSlate,
    fontFamily: 'Inter_600SemiBold',
  },
  mainTabLabelActive: {
    color: theme.colors.primary,
    fontWeight: theme.fontWeight.bold,
    fontFamily: 'Inter_700Bold',
  },
  mainTabIndicator: {
    position: 'absolute',
    bottom: 0,
    left: 6,
    right: 6,
    height: 3,
    borderRadius: 2,
    backgroundColor: theme.colors.primary,
  },

  // Records Sub-Tabs Row
  subTabRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: theme.spacing.lg,
    paddingTop: theme.spacing.lg,
    paddingBottom: theme.spacing.md,
  },
  subTab: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: theme.colors.surfaceSecondary,
    marginRight: theme.spacing.sm,
  },
  subTabActive: {
    backgroundColor: theme.colors.primary,
  },
  subTabText: {
    fontSize: 13,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textSecondary,
    fontFamily: 'Inter_600SemiBold',
  },
  subTabTextActive: {
    color: theme.colors.textInverted,
    fontWeight: theme.fontWeight.bold,
    fontFamily: 'Inter_700Bold',
  },
  subTabBadge: {
    marginLeft: 6,
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 10,
    backgroundColor: 'rgba(0,0,0,0.06)',
  },
  subTabBadgeActive: {
    backgroundColor: 'rgba(255,255,255,0.25)',
  },
  subTabBadgeText: {
    fontSize: 11,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.textSecondary,
    fontFamily: 'Inter_700Bold',
  },
  subTabBadgeTextActive: {
    color: theme.colors.textInverted,
  },
  addDocBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: theme.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 'auto',
  },
  addDocBtnText: {
    fontSize: 20,
    color: theme.colors.textInverted,
    fontWeight: '300',
    lineHeight: 24,
  },

  // Section Titles
  cardSectionTitle: {
    fontSize: theme.fontSize.md,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.textPrimary,
    marginBottom: theme.spacing.md,
    paddingHorizontal: theme.spacing.lg,
    fontFamily: 'Inter_700Bold',
  },

  // Record Card
  recordCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.borderRadius.lg,
    marginHorizontal: theme.spacing.lg,
    marginBottom: theme.spacing.md,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    overflow: 'hidden',
    ...globalShadows.card,
  },
  recordItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: theme.spacing.lg,
  },
  recordIconBox: {
    width: 44,
    height: 44,
    borderRadius: theme.borderRadius.md,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: theme.spacing.md,
  },
  recordIconText: {
    fontSize: 13,
    fontWeight: theme.fontWeight.bold,
    fontFamily: 'Inter_700Bold',
  },
  recordTitle: {
    fontSize: 15,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.textPrimary,
  },
  recordSub: {
    fontSize: theme.fontSize.xs,
    color: theme.colors.textSlate,
    marginTop: 2,
  },
  recordMeta: {
    fontSize: theme.fontSize.xs,
    color: theme.colors.textMuted,
    marginTop: 4,
  },
  pill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    alignSelf: 'flex-start',
  },
  pillText: {
    fontSize: 11,
    fontWeight: theme.fontWeight.bold,
  },
  shareRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: theme.colors.surfaceSecondary,
  },
  shareLabel: {
    fontSize: 12,
    fontWeight: theme.fontWeight.bold,
  },
  shareSub: {
    fontSize: 11,
    color: theme.colors.textMuted,
  },
  chevronText: {
    fontSize: 20,
    color: theme.colors.textMuted,
    marginLeft: 8,
  },

  // Empty State
  emptyState: {
    alignItems: 'center',
    paddingVertical: 48,
    paddingHorizontal: theme.spacing.xl,
  },
  emptyIconBox: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: theme.colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: theme.spacing.md,
  },
  emptyIconText: {
    fontSize: 20,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.primary,
  },
  emptyTitle: {
    fontSize: theme.fontSize.md,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.textSecondary,
    marginBottom: 4,
  },
  emptyText: {
    fontSize: theme.fontSize.xs,
    color: theme.colors.textMuted,
    textAlign: 'center',
  },

  // ── Consult Form Section Styles ──
  consultStepBarWrapper: {
    backgroundColor: theme.colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.surfaceBorder,
    flexDirection: 'row',
    alignItems: 'center',
  },
  consultStepTab: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  consultStepTabActive: {
    borderBottomColor: theme.colors.primary,
  },
  consultStepTabTitle: {
    fontSize: 12,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textSlate,
    fontFamily: 'Inter_600SemiBold',
    textAlign: 'center',
  },
  consultStepTabTitleActive: {
    color: theme.colors.primary,
    fontWeight: theme.fontWeight.bold,
    fontFamily: 'Inter_700Bold',
  },

  consultSectionCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.borderRadius.md,
    padding: theme.spacing.lg,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    ...globalShadows.card,
  },
  consultSectionTitle: {
    fontSize: theme.fontSize.md,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.textPrimary,
    marginBottom: theme.spacing.md,
    fontFamily: 'Inter_700Bold',
  },
  consultTextArea: {
    backgroundColor: theme.colors.background,
    borderRadius: theme.borderRadius.sm,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
    fontSize: theme.fontSize.sm,
    color: theme.colors.textPrimary,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    minHeight: 80,
  },
  consultInput: {
    backgroundColor: theme.colors.background,
    borderRadius: theme.borderRadius.sm,
    paddingHorizontal: theme.spacing.md,
    height: 44,
    fontSize: theme.fontSize.sm,
    color: theme.colors.textPrimary,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
  },
  vitalLabel: {
    fontSize: 12,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.textSecondary,
    marginBottom: 4,
  },
  vitalsRow: {
    flexDirection: 'row',
    marginBottom: theme.spacing.md,
  },
  vitalInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    borderRadius: theme.borderRadius.sm,
    backgroundColor: theme.colors.background,
    overflow: 'hidden',
    height: 44,
  },
  vitalInput: {
    flex: 1,
    paddingHorizontal: 12,
    fontSize: theme.fontSize.sm,
    color: theme.colors.textPrimary,
  },
  vitalUnitTag: {
    backgroundColor: theme.colors.surfaceSecondary,
    paddingHorizontal: 10,
    height: '100%',
    justifyContent: 'center',
    borderLeftWidth: 1,
    borderLeftColor: theme.colors.surfaceBorder,
  },
  vitalUnitText: {
    fontSize: 11,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.textSlate,
  },

  bmiContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    borderRadius: theme.borderRadius.sm,
    backgroundColor: theme.colors.background,
    height: 44,
    paddingHorizontal: 12,
  },
  bmiAutoTag: {
    backgroundColor: theme.colors.primarySoft,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: theme.colors.mintBdr,
  },
  bmiAutoText: {
    fontSize: 10,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.primary,
  },

  // Medication Card Elements
  medCardHead: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: theme.spacing.md,
  },
  medNumBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: theme.colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  medNumText: {
    fontSize: 12,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.primary,
  },
  medCardTitle: {
    fontSize: theme.fontSize.sm,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.textPrimary,
    flex: 1,
    fontFamily: 'Inter_700Bold',
  },
  removeText: {
    fontSize: 12,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.danger,
  },
  unitSelectBtn: {
    backgroundColor: theme.colors.surfaceSecondary,
    paddingHorizontal: 10,
    height: 44,
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    borderTopRightRadius: theme.borderRadius.sm,
    borderBottomRightRadius: theme.borderRadius.sm,
  },
  unitSelectText: {
    fontSize: 12,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.primary,
  },
  pickerSelectBtn: {
    backgroundColor: theme.colors.background,
    borderRadius: theme.borderRadius.sm,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    height: 44,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  pickerSelectText: {
    fontSize: theme.fontSize.sm,
    color: theme.colors.textPrimary,
  },

  // Buttons
  addOutlineBtn: {
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: theme.colors.primary,
    borderRadius: theme.borderRadius.sm,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addOutlineBtnText: {
    fontSize: 14,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.primary,
    fontFamily: 'Inter_700Bold',
  },
  addPrimaryBtn: {
    backgroundColor: theme.colors.primarySoft,
    borderWidth: 1,
    borderColor: theme.colors.mintBdr,
    borderRadius: theme.borderRadius.sm,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addPrimaryBtnText: {
    fontSize: 14,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.primary,
    fontFamily: 'Inter_700Bold',
  },
  draftBtn: {
    backgroundColor: theme.colors.surfaceSecondary,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    borderRadius: theme.borderRadius.sm,
    paddingVertical: 13,
    alignItems: 'center',
    marginTop: 8,
  },
  draftBtnText: {
    fontSize: 14,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.textSecondary,
    fontFamily: 'Inter_700Bold',
  },

  consultDateBtn: {
    backgroundColor: theme.colors.background,
    borderRadius: theme.borderRadius.sm,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    height: 44,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },

  // Sticky Bottom Navigation Bar
  consultStickyBottomBar: {
    backgroundColor: theme.colors.surface,
    borderTopWidth: 1,
    borderTopColor: theme.colors.surfaceBorder,
    paddingHorizontal: theme.spacing.lg,
    paddingTop: 10,
    paddingBottom: 24,
    ...globalShadows.glow,
  },
  autoSaveRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  autoSaveDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: theme.colors.success,
    marginRight: 6,
  },
  autoSaveText: {
    fontSize: 11,
    color: theme.colors.textSlate,
    fontWeight: theme.fontWeight.medium,
  },
  bottomBtnRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  btnPrev: {
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.colors.surfaceBorder,
    backgroundColor: theme.colors.surfaceSecondary,
  },
  btnPrevText: {
    fontSize: 14,
    fontWeight: theme.fontWeight.semibold,
    color: theme.colors.textSlate,
    fontFamily: 'Inter_600SemiBold',
  },
  btnNext: {
    flex: 1,
    backgroundColor: theme.colors.primary,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
  },
  btnNextText: {
    fontSize: 14,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.textInverted,
    fontFamily: 'Inter_700Bold',
  },
  btnComplete: {
    flex: 1,
    backgroundColor: theme.colors.primary,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
  },
  btnCompleteText: {
    fontSize: 15,
    fontWeight: theme.fontWeight.bold,
    color: theme.colors.textInverted,
    fontFamily: 'Inter_700Bold',
  },
});
